platform :ios, '8.0'
target 'KKXIU_LIVE' do
pod 'AFNetworking', '~> 2.6.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJRefresh', '~> 3.1.1'
pod 'MJExtension', '~> 3.0.10'
pod 'Masonry', '~> 1.0.1'
pod 'MBProgressHUD', '~> 0.9.2'
end
